version: '3.8'

services:
  couchdb:
    image: couchdb:3.3.1
    container_name: couchdb
    ports:
      - "5984:5984"  # Porta padrão do CouchDB
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: adminpassword
    networks:
      - project_so

  python-app:
    image: francinaldosb/python-app:latest
    container_name: python-app
    depends_on:
      - couchdb
    environment:
      COUCHDB_URL: http://admin:adminpassword@couchdb:5984
    ports:
      - "5000:5000"  # Porta da aplicação Python, se necessário
    networks:
      - project_so

networks:
  project_so:
    driver: overlay